# ABOUT PAGE CONTENT
about_name: "om-oss"
title: "Über Lauferkalender.de"
description: "Lauferkalender.de ist eine Sammlung von allen schwedischen Laufveranstaltungen. Hier finden Sie alle Rennen und Laufwettbewerbe in Deutschland 2024. Wir listen alle Rennen und Laufwettbewerbe in Deutschland 2024 auf. Finden Sie heute Ihren nächsten Meilenlauf, Zeitlauf, Trailrun, Halbmarathon, Marathon oder Ultramarathon bei uns."

# ABOUT PAGE
main_header: "Die umfassendste Liste von Langstreckenläufen in Deutschland"
paragraph1: |
  Willkommen bei der ultimativen Ressource für Laufbegeisterte in Deutschland!
  Unsere Website ist die umfassendste Liste von Laufveranstaltungen im Land und
  unser Ziel ist es, es einfacher denn je zu machen, Ihre nächste Herausforderung zu finden.
paragraph2: |
  Mit unserer benutzerfreundlichen Oberfläche können Sie die Rennen nach
  Entfernung, Art des Rennens und Ort filtern. Egal, ob Sie ein Anfänger sind,
  der nach seinem nächsten Meilenlauf sucht, oder ein Ultraläufer, der nach
  einem 100-Meilen-Rennen sucht, wir haben das Richtige für Sie. Unsere Mission ist es,
  prägnante, aber aktuelle Informationen zu allen Laufveranstaltungen in Deutschland
  bereitzustellen. Wir sind selbst aktive Läufer und Veranstalter von Wettkämpfen und
  überprüfen und erweitern kontinuierlich, um sicherzustellen, dass unsere Datenbank
  immer so korrekt und vollständig wie möglich ist. Sie können darauf vertrauen,
  dass wir zuverlässige Informationen zu Rennterminen, Orten und Anmeldeinformationen
  bereitstellen. Wenn es schwierig ist, sich an lauferkalender.de zu erinnern, finden Sie
  uns leicht, wenn Sie nach Schlüsselwörtern wie "Marathon Deutschland 2023" oder
  "Ultramarathon Deutschland" suchen.
paragraph3: |
  Neben unserer umfassenden Liste von Rennen ist es langfristig unser Ziel,
  auch Ressourcen und Tipps für Läufer auf allen Ebenen bereitzustellen.
  Von Trainingsplänen bis hin zur Ernährungsberatung möchten wir Ihre
  Anlaufstelle für alles rund um das Laufen sein. Treten Sie unserer
  Gemeinschaft leidenschaftlicher Läufer bei und bringen Sie Ihr
  Laufabenteuer auf die nächste Stufe.
paragraph4: |
  Wenn Sie Fragen oder Anmerkungen zum Inhalt haben, können Sie uns gerne
  unter folgender E-Mail-Adresse kontaktieren:
mail_to_link: "loppkartan@gmail.com"
add_new_race_box_header: "Genug über uns, finden Sie Ihr nächstes Rennen mit Hilfe der Karte oder der Liste unten:"
map_button_text: "KARTE"
list_button_text: "LISTE"
