# ADD RACE PAGE
add_race_name: "rennen-hinzufuegen"
map_message: "Platzieren Sie Ihr Rennen, indem Sie auf die Karte klicken"
date_text: "Datum"
type_text: "Art des Untergrunds / Art des Rennens"
type_select_placeholder: "Untergrund / Art des Rennens auswählen"
type_options:
  - "Straße"
  - "Gelände"
  - "Trail"
  - "Backyard Ultra"
  - "Staffel"
  - "Bahn"
  - "Sonstiges"
name_label: "Name des Rennens:"
name_placeholder: "z.B. Kungsholmen Rund"
distance_label: "Strecken:"
distance_placeholder: "10 km, Halbmarathon und Kinderlauf"
place_label: "Ort:"
place_placeholder: "Rålambshovsparken, Stockholm"
organizer_label: "Veranstalter:"
organizer_contact_placeholder: "FK Studenterna"
organizer_contact_label: "Kontaktperson E-Mail:"
organizer_mail_placeholder: "loppkartan@gmail.com"
website_label: "Veranstalter-Website:"
website_placeholder: "https://fkstudenterna.se/"
summary_label: "Beschreibung des Rennens"
summary_placeholder: "KfS Kungsholmen Runt ist eine Meilenstrecke mit langen, flachen Geraden ..."
preview_button: "Vorschau"
submit_button: "Senden"
preview_exit_button: "Zurück"
