collection_type: "Laufrennen"
sub_domain: rennen-seiten
icon_path: /img/logo.svg
page_type_text: "Seite für Laufrennen"

show_all_local: "Alle anzeigen"
url_text_top: "Link zur Anmeldung"
about_local: "Über das Rennen"
info_local: "Ausführliche Informationen"
disclaimer_text: |
  Alle Informationen auf dieser Seite basieren auf offenen Quelldaten. Wir tun unser Bestes, um sie aktuell zu halten, 
  können jedoch nicht garantieren, dass alles korrekt ist. Wenn Sie Fehler bemerken, kontaktieren Sie uns bitte 
  unter <a href="/kontakt.html">Kontakt</a>, damit wir sie so schnell wie möglich korrigieren können.

# Hauptlabels
main_labels: ["Strecken", "Untergrund", "Ort", "Datum"]
main_keys: ["display_distances", "type", "place", "date"]
icons: ["analytics", "shapes", "navigate-circle", "calendar-clear"]

# Komponenten
map: True
mapbox_center: "10.505557, 51.278809"
calendar: False

# Zusätzliche Labels
additional_labels: ["Rennkategorien", "Land", "Veranstalter"]
additional_keys: ["race_categories", "county", "organizer"]

url_text_bot: "Link zur Veranstalter-Website"
